name: ItemFrameDelayBlock
author: BrasilCraft
main: com.github.relativobr.ItemFrameDelayBlock
website: https://github.com/RelativoBR/ItemFrameDelayBlock
api-version: 1.16
version: ${project.version}
softdepend: []
